# Generated by Django 4.0.4 on 2022-04-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideaBoatApp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlikes',
            old_name='like',
            new_name='likes',
        ),
    ]
