# Generated by Django 4.0.4 on 2022-04-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideaBoatApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_category',
            options={},
        ),
    ]
