# Generated by Django 4.0.4 on 2022-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaBoatApp1', '0002_alter_post_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_category',
            name='name',
            field=models.CharField(choices=[('AI', 'AI'), ('WEB APPLICATION', 'WEB APPLICATION'), ('ML', 'ML'), ('EMBEDDED SOFTWARE', 'EMBEDDED SOFTWARE'), ('HARDWARE', 'HARDWARE')], default='WEB APPLICATION', max_length=100),
        ),
    ]
