# Generated by Django 4.0.4 on 2022-04-26 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideaBoatApp1', '0005_alter_comment_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='PostLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
