# Generated by Django 4.0.4 on 2022-04-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaBoatApp1', '0009_remove_post_comments_postlikes_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlikes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AddField(
            model_name='postlikes',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
